---
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: show flake show
    commands:
      - nix flake show

  - name: show flake info
    commands:
      - nix flake info

---
kind: pipeline
type: exec
name: build for x86 CPU's

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build for x86_64-linux - without CUDA
    commands:
      - nix build .#whisper_bench --out-link result-whisper_bench

  - name: build for x86_64-linux - with CUDA
    commands:
      - nix build .#whisper_bench_withCUDA --out-link result-whisper_bench_withCUDA

  - name: upload to binary cache via s3
    commands:
      - nix run 'github:mayniklas/nixos'#s3uploader
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret
